### ISSUE TITLE
Fix SyntaxError handling

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.PythonScripts#11]
When entering code containing a `SyntaxError` an error page is shown. Previously a warning was rendered above the text area containing the code.

# Before (Zope 2.13):
![before](https://user-images.githubusercontent.com/386619/31894883-f5033be8-b80f-11e7-8707-e98336821b30.png)

# After (Zope 4):

![after](https://user-images.githubusercontent.com/386619/31894884-f52788c2-b80f-11e7-81b5-d1cfc18ea4de.png)

Besides the error page shown the changes are not saved!
Maybe this is caused by the changes in RestrictedPython.

**Comment by hannosch** [comment]
This might also be caused by changing some bare `try/except` to a `try/except Exception`. I think `SyntaxError` is derived from `BaseException` and thus might not be caught anymore.

**Comment by jamadden** [comment]
`SyntaxError` appears to be an `Exception`:

```pycon
Python 2.7.14 (default, Sep 27 2017, 12:15:00)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> SyntaxError.mro()
[<type 'exceptions.SyntaxError'>,
 <type 'exceptions.StandardError'>,
 <type 'exceptions.Exception'>,
 <type 'exceptions.BaseException'>,
 <type 'object'>]
```
```pycon
Python 3.4.7 (default, Sep 27 2017, 15:47:41)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> SyntaxError.mro()
[<class 'SyntaxError'>,
 <class 'Exception'>,
 <class 'BaseException'>,
 <class 'object'>]
>>>
```

**Comment by tseaver** [comment]
I'd prefer not to close bugs via PR merges in another repository:  the bug here won't really be fixed until a new release of `RestrictedPython` is available.

**Comment by icemac** [comment]
@tseaver You are right, additionally `Products.PythonScripts` should depend on the new release to be able to leverage the bug fix here.

**Comment by tseaver** [comment]
@icemac Thanks for fixing the pin!
