### ISSUE TITLE
Default script content uses deprecated print statements

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Products.PythonScripts#26]
When creating a Python Script in the ZMI and not uploading a file straight away the script will be created with default content. This content uses `print` the old-style way and the `Ace` editor will show error messages straight away. Fix the default content to not show errors.

**Comment by dataflake** [comment]
This is half fixed with 14351bf8f3c74da2b8c75579dc5a39dcdbd9994a. As it turns out, RestrictedPython under Python 2 does not (yet) distinguish which kind of `print` is used, the old-fashioned statement or the newer function call. Once RestrictedPython is fixed this can be re-checked and closed.

**Comment by icemac** [comment]
The issue in RestrictedPython is zopefoundation/RestrictedPython#155.

**Comment by dataflake** [comment]
I'm going to close this issue here because there's nothing we can do in this package to solve it.
