### ISSUE TITLE
isinstance not working with list

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Products.PythonScripts#52]
When I execute this code in a Python script:

```
mylist = []
isinstance(mylist, list)
```

I get the following error: "isinstance() arg 2 must be a type or tuple of types".

The other types work well, but I can't seem to check the instance type for a list in this way.

### What version of Python and Zope/Addons I am using:
OS: MacOs Catalina and FreeBSD 12
Python: 3.8.6
Zope 5.3

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2022-3-27 13:38 -0700:
>When I execute this code in a Python script:
>
>```
>mylist = []
>isinstance(mylist, list)
>```
> ... isinstance() arg 2 must be a type or tuple of types ...

The `list` in a restricted environment is not the type `list`,
while list objects are "normal" lists.

Using the normal `list` in a restricted environment would likely
allow to circumvent the security restrictions.
Therefore, `list` in a restricted environment is something special.

You can use the function `same_type` to check whether an
object is a list: `same_type(obj, [])`.

**Comment by georgpfolz** [comment]
Thank you! I wasn't aware of that! Also, `type(mylist)` not being allowed in restricted Python, I was at a loss how to perform the check. `same_type` solves it for me!

**Comment by dataflake** [comment]
By the way, `same_type` is documented, but I realize it may be hard to find: https://zope.readthedocs.io/en/latest/zopebook/BasicScripting.html?highlight=same_type#built-in-functions

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2022-3-28 00:45 -0700:
>By the way, `same_type` is documented, but I realize it may be hard to find: https://zope.readthedocs.io/en/latest/zopebook/BasicScripting.html?highlight=same_type#built-in-functions

Accorting to the OP, `isinstance` works for "some types other than `list`.
I do not know which types he has tried but e.g. `dict` should
have security concerns similar to `list` (also accepting an
iterator). Thus, if we have a solution for those types, it might
be applied to `list` as well.

Of course, a task for `AccessControl` not `PythonScripts`.

**Comment by georgpfolz** [comment]
> By the way, same_type is documented, but I realize it may be hard to find

Yes, especially if one does not suspect it exists ;)

> I do not know which types he has tried

I did not try them all, that's why I didn't notice that `dict` also does not work

**Comment by icemac** [comment]
AccessControl defines what `list` means here: https://github.com/zopefoundation/AccessControl/blob/be8cd148a208052ba3b6a17d617e9c1d275f5068/src/AccessControl/ZopeGuards.py#L448 There are several other built-ins redefined to make them more secure.
