### ISSUE TITLE
func_code and func_defaults are not available on python 2 scripts.

### ISSUE THREAD

**Issue by perrinjerome** [zopefoundation/Products.PythonScripts#55]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

`func_code` and `func_defaults` are not available on python 2 scripts.

### What I did:

I updated an instance created on Zope 2.13.30 with python scripts to run on Zope 4 on python 2, using a custom application which uses `func_code` and `func_defaults` on python scripts.

### What I expect to happen:

I expected `func_code` and `func_defaults` to be available on scripts. Even though python2 had support for the modern equivalent `__code__` and `__defaults__`, it still uses `func_code` and `func_defaults` in some places, for example in the inspect module. This was also documented as the way to get the code object from a function ( https://docs.python.org/2.7/library/stdtypes.html#code-objects )

### What actually happened:

When I create a new scripts on Zope 4, `func_code` and `func_defaults` is not set ( `AttributeError: 'PythonScript' object has no attribute 'func_code'`).

For existing scripts, `func_code` and `func_defaults` was set, because it had been set when the script was created on Zope 2, but editing the script only updates `__code__` and `__defaults__`, `func_code` and `func_defaults` are still using the old values from the time the script was created on Zope 2 and are never updated.

### What version of Python and Zope/Addons I am using:

before upgrade:

* Products.PythonScripts  2.13.2
* Zope 2.13.30
* Python 2.7.13

after upgrade:

* Products.PythonScripts on master branch
* Zope 4.8.1
* Python 2.7.13

**Comment by perrinjerome** [comment]
I have identified that this can be fixed by a change in Zope, on the 4.X branch because master branch dropped python 2 support and I have included some tests to reproduce the issue in https://github.com/zopefoundation/Products.PythonScripts/pull/56 

Maybe this issue should be moved to Zope repository, I was not sure.

Thanks in advance, I hope the explanation is clear enough and that it's not too late to bring some python 2 only fixes.

**Comment by dataflake** [comment]
Fixed in Zope version 4.8.2
